config/routes.rb
Rails.application.routes.draw do

  get "search/index"

  get "search/search"

  get "account/index"

  get '/' => 'chat#index', :as => :index

  get '/about' => 'application#about'

  root :to => 'chat#index'

  namespace(:api) do
    namespace(:v1) do
      get 'room/list', :controller => 'room', :action => 'list'
      get 'message/list', :controller => 'message', :action => 'list'
      get 'message/search', :controller => 'message', :action => 'search'
      delete 'message/destroy(/:id)', :controller => 'message', :action => 'destroy'
      get 'user', :controller => 'user', :action => 'show'
      post 'user', :controller => 'user', :action => 'update'
      get 'user/add_device', :controller => 'user', :action => 'add_device'
      post 'user/add_device', :controller => 'user', :action => 'add_device'
      post 'user/delete_device', :controller => 'user', :action => 'delete_device'
      post 'room/add_member/:id', :controller => 'room', :action => 'add_member'
      resources :room
      resources :message
      get 'login', :controller => 'login', :action => 'index'
      get 'service/info', :controller => 'service', :action => 'info'
    end
  end

  get 'chat/room(/:id)' => "chat#room", :as => "chat_room"

  match 'room/configure/:id' => "room#configure", :as => "room_configure", :via => [:get, :post]

  get 'message', '/chat/show/:id', :controller => "chat", :action=> "show"

  match '/auth/:provider/callback', :to => 'login#omniauth_callback', :via => [:get, :post]
  get '/auth/failure', :to => 'login#failure'
  get '/login/index', :controller => 'login', :action => 'index'
  post '/login/logout', :controller => 'login', :action => 'logout'

  get '/plugin/:plugin/:type/:file.:format', :to => 'plugin#asset', :as => :plugin_asset

  match 'rooms/create', :controller => 'room', :action => :create, :via => [:get, :post]
  match 'rooms/delete/:id', :controller => 'room', :action => :delete, :via => [:get, :post]
  match 'rooms/configure(/:id)', :controller => 'room', :action => :configure, :via => [:get, :post]

  get 'chat/index', :controller => 'chat', :action => :index
  get 'chat/show/:id', :controller => 'chat', :action => :show
  match 'chat/message', :controller => 'chat', :action => :message, :via => [:get, :post]

  get 'search', :controller => 'search', :action => :index
  get 'search/search', :controller => 'search', :action => :search
  get 'search/search_more', :controller => 'search', :action => :search_more

  Dir.glob(Rails.root+'plugins'+'*'+'config'+'routes.rb') do |routes|
    instance_eval File.read(routes)
  end
end

app/views/shared/_room_info.html.haml
-# -*- coding: utf-8 -*-
%div.room-info
 %div
  .left
   %h3.title
    = link_to room.title, chat_room_path(room)

  - if has_button
   .right
    =image_tag('private.png', :class => 'icon', :alt => t(:private_room), :title => t(:private_room)) unless room.is_public
    =image_tag("connection_fail.png", :class => 'icon websocket-status', :alt => t(:websocket_status), :title => t(:websocket_status))
    - if logged?
     = link_to(image_tag("config.png", :class => 'icon', :alt => t(:config), :title => t(:config)), room_configure_path(room))
     = form_tag({:controller => :room, :action => :delete, :id => room.id.to_s}, {:onsubmit => "return confirm('#{t(:are_you_sure_you_want_to_delete_this_room)}');", :action => :post, :class => 'delete-form'}) do
      = image_submit_tag "room_delete.png", :class => 'icon', :alt => t(:delete_this_room), :title => t(:delete_this_room)
  .clear
 - unless room.user.nil?
  %div.room-owner
   = t(:room_created_by) + " "
   %img.profile{:src => room.user.profile_for(room.id)[:profile_image_url], :alt => room.user.screen_name, :alt => room.user.screen_name}
   = room.user.profile_for(room.id)[:name]
 %div.room-date
  = t(:created_at) + " " + l(room.created_at)
 - unless room.is_public
  %div.room-members
   - room.members.each do |member|
    %img.profile{:src => member.profile_for(room.id)[:profile_image_url], :alt => member.screen_name, :title => member.screen_name}